### ISSUE TITLE
TypeError: %X format: a number is required, not Dot11WEP

### ISSUE THREAD

**Issue by pcarmo** [ICSec/pyDot11#31]
Hi, I'm not sure if I'm doing anything wrong, but this errors keeps showing up.
The only thing I do is to load a cap file and for each packet I verify if the it has Dot11 layer.
If it's positive, then I run wpaDecrypt with the arguments as descripted below.

Traceback (most recent call last):
  File "get_info.py", line 26, in <module>
    p = wpaDecrypt("passphrase", p ,"ccmp")
  File "/usr/local/lib/python2.7/dist-packages/pyDot11/__init__.py", line 47, in wpaDecrypt
    stream, PN = ccmpCrypto.decoder(origPkt, encKey)
  File "/usr/local/lib/python2.7/dist-packages/pyDot11/lib/ccmp.py", line 106, in decoder
    output = 'str')
  File "/usr/local/lib/python2.7/dist-packages/packetEssentials/lib/utils.py", line 57, in byteRip
    stream = hexstr(stream, onlyhex = 1)
  File "/home/pcarmo/.local/lib/python2.7/site-packages/scapy/utils.py", line 186, in hexstr
    s.append(" ".join("%02X" % orb(b) for b in x))
  File "/home/pcarmo/.local/lib/python2.7/site-packages/scapy/utils.py", line 186, in <genexpr>
    s.append(" ".join("%02X" % orb(b) for b in x))
TypeError: %X format: a number is required, not Dot11WEP

**Comment by stryngs** [comment]
@pcarmo Which version of Python are you performing this in?

**Comment by pcarmo** [comment]
I've got this in both 2.7 and 3.6 versions

**Comment by stryngs** [comment]
Hi @pcarmo can you provide a copy of the pcap you are working with, or find one that yields that error and share it?

**Comment by pcarmo** [comment]
Hi @stryngs, here it is. 
Hope you find it useful.
https://drive.google.com/open?id=1klgfLERuKH3TuJPVm-e92fhkyg7Ythet

**Comment by stryngs** [comment]
Closing this issue out.  If wanted follow up with a PR on https://github.com/stryngs/pyDot11.
